site_name: NixOS-pcsd

repo_url: https://github.com/matt1432/nixos-pcsd

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
